USE [master]
GO

/****** Object:  Database [SeguroAutomovel]    Script Date: 19/06/2020 13:21:48 ******/
CREATE DATABASE [SeguroAutomovel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SeguroAutomovel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SeguroAutomovel.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SeguroAutomovel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SeguroAutomovel_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SeguroAutomovel] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SeguroAutomovel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SeguroAutomovel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET ARITHABORT OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SeguroAutomovel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SeguroAutomovel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SeguroAutomovel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SeguroAutomovel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SeguroAutomovel] SET  MULTI_USER 
GO

ALTER DATABASE [SeguroAutomovel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SeguroAutomovel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SeguroAutomovel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SeguroAutomovel] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SeguroAutomovel] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SeguroAutomovel] SET  READ_WRITE 
GO


